name: update-predictors
on:
  workflow_dispatch
env:
  # jdk-version: openjdk@~1.15.0
  project-name: psyke-pytest
  workflow: update-predictors
  # gradle-options: "--no-daemon --console=plain --stacktrace"
jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: | 
          python --version
          pip --version

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      # - name: Get All Tags
      #   run: git fetch --tags -f

      - name: Update predictors
        run: python update_predictors
